### ISSUE TITLE
Sample app does not delete aborted large file

### ISSUE THREAD

**Issue by brucejo75** [vsivsi/meteor-file-sample-app#7]
I am pretty interested in the [file-collection](https://github.com/vsivsi/meteor-file-collection) package and I cloned the sample app.

When I run the app it is pretty great.  But I noticed that if I upload a very large file, then abort it; all the data remains in the Mongo DB.

I suspect the underlying [file-collection](https://github.com/vsivsi/meteor-file-collection) package.  This line looks a little suspicious to my untrained eye:
[https://github.com/vsivsi/meteor-file-collection/blob/master/src/gridFS_server.coffee#L145](https://github.com/vsivsi/meteor-file-collection/blob/master/src/gridFS_server.coffee#L145)
### Repro
1. clone sample.
2. run `meteor`
3. try sample app.
4. upload a 3GB file, it takes a while to upload.
5. after 2% or so, abort the upload.
6. file is removed from the UI.
### Observed

All of the fs.files, fs.chunks and fs.locks data is still in the DB.
Actually, I noticed that one fs.file and one fs.lock was indeed deleted.  But no fs.chunks were deleted.
### Expected

All of the fs.files, fs.chunks and fs.locks to be removed.

**Comment by vsivsi** [comment]
Hi, thanks for reporting. As far as file-collection is concerned, your expected outcome is incorrect. The observed behavior is by design (for file-collection).

Why? You are probably asking yourself...  Because uploads are designed to be resumable. So if your internet drops and later recovers, or you close your laptop to go to a meeting and then come back and wake it up, you don't need to start the file upload again. The included resumable.js upload package supports this directly (hence the name!) It is meant to be resilient for very large uploads over unreliable networks. The only way for the server side to accomplish this is to (temporarily) keep the upload state, so if the upload is later resumed, it can pick up where it left off. So file-collection is working correctly.

Now, this "sample app" is just that. It doesn't implement all possible functionality that a more sophisticated and robust application might (the back-end is 30 lines of code!) In this case, it doesn't have any logic to decide when to "give up" on an upload and clean-up. This leads to the partial upload data you've observed remaining in the database. 

The underlying file-collection package, by design, doesn't implement any policy regarding when to clean-up partially uploaded files. But implementing such a policy is only a handful of lines of code, and different applications will have wildly different requirements, so it is left unspecified. 

Right now there are two ways in the sample app that fragments of partially uploaded files can remain:
1.    Aborting the download by deleting the file in the client.
2.    Closing the uploading browser window, unplugging the internet, powering off the computer, etc.

1) Can be fixed on the server by creating a query `observe` for removal of zero length files. When such a remove is observed, it can go look for any one chunk temporary files associated with the upload and delete them.

2) Are legitimate "resumable" upload scenarios. To "fix" these cases, the server needs to implement an upload timeout policy (say 48 hours) where partial uploads are aborted and cleaned up once the timeout has passed since the most recent chunk has been received.

If you'd like to try your hand at implementing 1) and/or 2) in the sample app, I'll happily consider a PR.

**Comment by brucejo75** [comment]
Awesome!  I will take a look.  Thanks for super fast response.
